In 'short' testmod, use OCN_NCPL instead of ATM_NCPL
Trying to use ATM_NCPL leads to:
ERROR: assume that rof_cpl_time is always greater than or equal to ocn_cpl_time